apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source-to-broker
spec:
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  consumerGroup: a
  topics:
    -
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: <todo>